### ISSUE TITLE
CSP Support

### ISSUE THREAD

**Issue by Springstone** [projectkudu/ARMClient#25]
It looks like CSP support is missing, or I can't figure out how to implement it. The SPN command hints at this being possible, but for tenants created under a service provider, we don't know what the passphrase is... so using "armclient spn <tenantid> <appid>" doesn't work. Maybe I'm missing something. I login as the AOBO user, and have 0 subscriptions, which is correct, because my tenants have subscriptions. I can't figure out how to select the tenant using my AOBO credentials.

**Comment by suwatch** [comment]
We do support this scenario in latest ARMClient 1.1.1.0 (since last year).   The key is to set [ARMCLIENT_TENANT](https://github.com/projectkudu/ARMClient/commit/9b178630d9e3640317638249b41613674addc276) env to tenant you want to login to (briefly documented [here](https://github.com/projectkudu/ARMClient/wiki/Login-and-Acquire-Tokens)) before calling ARMClient login (or get etc.).
